spring.application.name=ms-auth
server.port=8081

eureka.client.enabled=false

# PostgreSQL Neon Database
spring.datasource.url=jdbc:postgresql://ep-calm-credit-acr8cprb-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IM7CVkGct5Qb
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# Security JWT
security.jwt.private.key=${PRIVATE_KEY:MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC7}
security.jwt.user.generator=${USER_GENERATOR:test@qualitytrack.com}

# Logging
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=INFO

# Management
management.endpoints.web.exposure.include=health,info
