spring.application.name=qualititrack


#Configuraciones de seguridad
spring.security.user.name=${SS_USER}
spring.security.user.password=${SS_PASSWORD}

#Configuraciones de BDD
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/qualitytrack_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

#Configuraciones de JWT
security.jwt.private.key=${PRIVATE_KEY}
security.jwt.user.generator=${USER_GENERATOR}